name: Matrix Strategy Include Sample
# The trigger event 
on: push
# The jobs to run
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-latest,macos-11,]
        node: [4, 6, 8]
        include:
          - os: macos-latest
            node: 8
            npm: 8a
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.npm }}
        run: npm install -g yarnpkg --save-dev --force
      - run: npm install docker -g --save --force
