name: Install GNU Guix
description: Add GNU guix package manager to GitHub Action runner.
branding:
  icon: package
  color: gray-dark
inputs:
  channels:
    description: Guix channel description as Scheme code
    required: false
    default: |-
      (map (lambda (chan)
             (if (guix-channel? chan)
                 (channel
                  (inherit chan)
                  (url "https://github.com/guix-mirror/guix.git"))
                 chan))
           %default-channels)
outputs:
  channels:
    description: Exact Guix channels that were used for this action.
    value: ${{ steps.guix-describe.outputs.channels }}
runs:
  using: composite
  steps:
    - run: echo LANG=en_US.utf8 >> $GITHUB_ENV
      shell: bash
      name: Set LANG
    - run: >
        wget -nv
        https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh -O
        guix-install.sh

        wget -nv https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz -O guix-binary-nightly.x86_64-linux.tar.xz
      shell: bash
      name: Download
    - run: >
        wget "https://sv.gnu.org/people/viewgpg.php?user_id=127547" -qO - | sudo
        gpg --import -

        wget "https://sv.gnu.org/people/viewgpg.php?user_id=15145" -qO - | sudo gpg --import -
      shell: bash
      name: Fetch key
    - run: >
        export GUIX_BINARY_FILE_NAME=guix-binary-nightly.x86_64-linux.tar.xz

        sudo --preserve-env=GUIX_BINARY_FILE_NAME -- bash -c 'yes | bash guix-install.sh'
      shell: bash
      name: Install Guix
    - run: sudo -i guix archive --generate-key
      shell: bash
      name: Generate keys
    - run: |
        cat <<EOF > ${{ runner.temp }}/channels.scm
        ${{ inputs.channels }}
        EOF
      shell: bash
      name: Create channel file
    - run: guix pull --fallback -C ${{ runner.temp }}/channels.scm
      shell: bash
      name: Update Guix
    - run: |
        sudo sed -i "s/root/${USER}/" /etc/systemd/system/guix-daemon.service
        sudo systemctl daemon-reload
        sudo systemctl restart guix-daemon
      shell: bash
      name: Restart daemon
    - run: |
        echo "$HOME/.config/guix/current/bin" >> $GITHUB_PATH
      shell: bash
      name: Set PATH
    - run: >
        echo "::set-output name=channels::$(guix describe -f channels | tr '\n' '
        ')"
      shell: bash
      name: guix describe
      id: guix-describe
